version: '3.7'

services:

  chinook-database:
    image: schemacrawler/chinook
    stdin_open: true
    tty: true
    volumes:
      - type: bind
        source: ./
        target: /home/chinook/output
